services:
  postgres:
    image: postgres
    container_name: chatroom-db
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - golang

networks:
  golang:

volumes:
  postgres_data:
